### PR TITLE
feat: decode callback parameter adds key

### PR DESCRIPTION
**Pull request by yxw007**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Relate issuse：[Decode function for useCookie called for every cookie present](https://github.com/nuxt/nuxt/issues/27246)

Example：
image

Reason：
image
image

When useCookie('bar',..), document.cookie = "foo=FOO; bar=BAR", the parse function will traverse each cookie and then decode As a result, foo cookie will also call barCookie decode, which is unreasonable. So my idea is to return one more key field when parse, so that the upper layer can filter out the decode that does not belong to the current key.

### CODE REVIEW

**Comment by pi0** [comment]
Thanks for this PR.

I think it is an interesting idea to pass the `key` object to the custom `decode` method but for the purpose of filtering the key to decode only, (#31) it might be overkill:

- [value normalization](https://github.com/unjs/cookie-es/blob/d29fc147101f16a839784240a91751ee93023595/src/index.ts#L56C1-L61C8) happens before we hit the custom decode function that can filter 
- Purpose of decode function should be decoding not handling filter logic. not only it makes usage more complicated and less readable but also might result in encouraging to diverge from `cookie-es` default decode behavior

Because of this i think we should think of a better way to explicitly support key filter

**Comment by yxw007** [comment]
> Thanks for this PR.
> 
> I think it is an interesting idea to pass the `key` object to the custom `decode` method but for the purpose of filtering the key to decode only, (#31) it might be overkill:
> 
> * [value normalization](https://github.com/unjs/cookie-es/blob/d29fc147101f16a839784240a91751ee93023595/src/index.ts#L56C1-L61C8) happens before we hit the custom decode function that can filter
> * Purpose of decode function should be decoding not handling filter logic. not only it makes usage more complicated and less readable but also might result in encouraging to diverge from `cookie-es` default decode behavior
> 
> Because of this i think we should think of a better way to explicitly support key filter

You are right, it is indeed the case. I will think about it and see if there is a better way to solve it. Of course, if you have any good suggestions, please tell me.

**Comment by pi0** [comment]
I think we can add new `options.filter(key)` option support and use it after L52

**Comment by yxw007** [comment]
> I think we can add new `options.filter(key)` option support and use it after L52

image
image

May I ask if my understanding is correct ?

**Comment by pi0** [comment]
Seems good only similar to js array filter() when a truehy value is returned i think we want to parse otherwise skip

**Comment by yxw007** [comment]
> Seems good only similar to js array filter() when a truehy value is returned i think we want to parse otherwise skip

Okay, I'll adjust the judgment conditions

**Pull request closed without merging**
