### PR TITLE
feat: add `partitioned` option

### PR DESCRIPTION
**Pull request by AlexXanderGrib**
Spec: https://developer.mozilla.org/en-US/docs/Web/Privacy/Partitioned_cookies

- Added `partitioned` option to cookie serialization. 
- Added tests and run lint:fix

### CODE REVIEW

**Comment by fmoessle** [comment]
Would love to see this one merged and used in h3 and nitro. Google is starting to `phase out third-party cookies for everyone in the second half of 2024` [link](https://blog.google/products/chrome/privacy-sandbox-tracking-protection/amp/). Partitioned cookies is one of the suggested methods by google for dealing with this.

**Comment by AlexXanderGrib** [comment]
jshttp/cookie#153 already added partitioned support into upstream. Can this be merged?

**Comment by adarshmadrecha** [comment]
Looking forward to release with this feature.

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
Thanks.

**Pull request merged**
